all: subsystems

subsystems:
	@cd ExceptionSafeHandleBody && $(MAKE)
	@cd ObjectFactories && $(MAKE)
	@cd SmartPointers && $(MAKE)
	

clean:
	@cd ExceptionSafeHandleBody && $(MAKE) clean
	@cd ObjectFactories && $(MAKE) clean
	@cd SmartPointers && $(MAKE) clean


