#! /bin/sh

g++ -c -std=c++20 -fmodules-ts -x c++-system-header iostream
g++ -c -std=c++20 -fmodules-ts 01.helloWorld.cpp
g++ -c -std=c++20 -fmodules-ts 01.main.cpp
g++ 01.helloWorld.o 01.main.o -o main.exe
