all: subsystems

subsystems:
	@cd NamespaceExamples && $(MAKE)
	@cd NamespacesInLibraries && $(MAKE)

clean:
	@cd NamespaceExamples && $(MAKE) clean
	@cd NamespacesInLibraries && $(MAKE) clean


