include make.mk

all: subsystems
	
subsystems:
	@cd Accumulators && $(MAKE)
	@cd Any && $(MAKE)
	@cd Arrays && $(MAKE)
	@cd Assign && $(MAKE)
	@cd BindAndFunction && $(MAKE)
	@cd Conversion && $(MAKE)
	@cd DateTime && $(MAKE)
	@cd FileSystem && $(MAKE)
	@cd Lambda && $(MAKE)
	@cd Pools && $(MAKE)
	@cd RegEx && $(MAKE)
#	@cd Spirit && $(MAKE)
	@cd Threads && $(MAKE)
#	@cd Tuples && $(MAKE)
	@cd uBLAS && $(MAKE)
	@cd FileSystem && $(MAKE)
	

clean:
	@cd Accumulators && $(MAKE) clean
	@cd Any && $(MAKE) clean
	@cd Arrays && $(MAKE) clean
	@cd Assign && $(MAKE) clean
	@cd BindAndFunction && $(MAKE) clean
	@cd Conversion && $(MAKE) clean
	@cd DateTime && $(MAKE) clean
	@cd FileSystem && $(MAKE) clean
	@cd Lambda && $(MAKE) clean
	@cd Pools && $(MAKE) clean
	@cd RegEx && $(MAKE) clean
#	@cd Spirit && $(MAKE) clean
	@cd Threads && $(MAKE) clean
#	@cd Tuples && $(MAKE) clean
	@cd uBLAS && $(MAKE) clean


