CC := g++
CFLAGS := -g -std=c++11 -Wall 
LFLAGS := -L C:/cygwin/lib/w32api


all: ThreadsPools.exe

ThreadsPools.exe: *.cpp
	$(CC) $(CFLAGS) $(LFLAGS) *.cpp -o $@

clean:
	rm *.exe
	
	

