all: subsystems

subsystems:
	@cd ChainOfResponsibility && $(MAKE)
	@cd Iterator && $(MAKE)
	@cd Observer && $(MAKE)
	@cd State && $(MAKE)
	@cd Strategy && $(MAKE)
	@cd Visitor && $(MAKE)
	

clean:
	@cd ChainOfResponsibility && $(MAKE) clean
	@cd Iterator && $(MAKE) clean
	@cd Observer && $(MAKE) clean
	@cd State && $(MAKE) clean
	@cd Strategy && $(MAKE) clean
	@cd Visitor && $(MAKE) clean


