all: subsystems

subsystems:
	@cd Composite && $(MAKE)
	@cd DoubleDespatch && $(MAKE)
	@cd ModelViewController && $(MAKE)
	@cd NVI && $(MAKE)
	@cd Undo && $(MAKE)
	

clean:
	@cd Composite && $(MAKE) clean
	@cd DoubleDespatch && $(MAKE) clean
	@cd ModelViewController && $(MAKE) clean
	@cd NVI && $(MAKE) clean
	@cd Undo && $(MAKE) clean


