include ../../../Build/make.mk
# LFLAGS := -static -lboost_regex
LFLAGS := -v -shared -fPIC -L/usr/lib -Wl,libboost_regex.so # -Wl,--export-dynamic
CFLAGS := -I /home/chris/Downloads/boost_1_75_0


# The Boost C++ Libraries were successfully built!
# 
# The following directory should be added to compiler include paths:
# 
    # /home/chris/Downloads/boost_1_75_0
# 
# The following directory should be added to linker library paths:
# 
    # /home/chris/Downloads/boost_1_75_0/stage/lib

