WARNINGS := -Wno-unused-private-field -Wno-uninitialized
export WARNINGS
include ../Build/make.mk
WARNINGS := -Wno-unused-private-field -Wno-uninitialized
export WARNINGS


cleanup:
	rm mempool1 mempool2

