all: subsystems

subsystems:
	cd Containers && $(MAKE)
	cd Algorithms && $(MAKE)
	cd UsingSTLEfficiently && $(MAKE)
	cd Ranges && $(MAKE)

	

clean:
	@cd Containers && $(MAKE) clean
	@cd Algorithms && $(MAKE) clean
	@cd UsingSTLEfficiently && $(MAKE) clean
	@cd Ranges && $(MAKE) clean
	
	
	
