include ../Build/make.mk
CFLAGS := -fcoroutines -fno-exceptions $(CFLAGS)
LFLAGS = -lpthread
export LFLAGS

#all:
#	g++ -g -std=c++20 -fcoroutines -fno-exceptions 1.cpp -o 1.exe
#	g++ -g -std=c++20 -fcoroutines -fno-exceptions 2.cpp -o 2.exe
#	g++ -g -std=c++20 -fcoroutines -fno-exceptions 3.cpp -o 3.exe
