all: subsystems

subsystems:
	@echo "\n\n";cd NamespaceExamples && $(MAKE)
	@echo "\n\n";cd NamespacesInLibraries && $(MAKE) main

clean:
	@echo "\n\n";cd NamespaceExamples && $(MAKE) clean
	@echo "\n\n";cd NamespacesInLibraries && $(MAKE) clean


