#! /bin/sh
################################################################
#
# This script will use CMakeLists.txt to build all examples
#
################################################################

clear
cmake -S . -B build
cmake --build build
