WARNINGS := -Wno-unused-private-field
export WARNINGS
include ../Build/make.mk
CFLAGS := -I /home/chris/anaconda3/include/python3.7m
LFLAGS := -fPIC -shared -Wl,--export-dynamic -lboost_python3 

