all: subsystems

subsystems:
	@cd 1.Behavioural && $(MAKE)
	@cd 2.Creational && $(MAKE)
	@cd 3.Structural && $(MAKE)
	@cd 4.RealTime && $(MAKE)
	@cd 5.Miscellaneous && $(MAKE)
	@cd 6.C++Specific && $(MAKE)
	

clean:
	@cd 1.Behavioural && $(MAKE) clean
	@cd 2.Creational && $(MAKE) clean
	@cd 3.Structural && $(MAKE) clean
	@cd 4.RealTime && $(MAKE) clean
	@cd 5.Miscellaneous && $(MAKE) clean
	@cd 6.C++Specific && $(MAKE) clean


