# https://www.walletfox.com/course/examples_range_v3.php
# https://ericniebler.github.io/range-v3/


include ../../Build/make.mk
CFLAGS := $(CFLAGS) -I ../../vcpkg/packages/range-v3_x64-linux/include




