all: subsystems

subsystems:
	@cd NamespaceExamples && $(MAKE)
	@cd NamespacesInLibraries && $(MAKE) Test

clean:
	@cd NamespaceExamples && $(MAKE) clean
	@cd NamespacesInLibraries && $(MAKE) clean


