all: subsystems

subsystems:
	@cd AbstractFactory && $(MAKE)
	@cd Builder && $(MAKE)
	@cd FactoryMethod && $(MAKE)
	@cd Singleton && $(MAKE)
	

clean:
	@cd AbstractFactory && $(MAKE) clean
	@cd Builder && $(MAKE) clean
	@cd FactoryMethod && $(MAKE) clean
	@cd Singleton && $(MAKE) clean


