all: subsystems

subsystems:
	@cd AdaptorClass && $(MAKE)
	@cd AdaptorObject && $(MAKE)
	@cd Bridge && $(MAKE)
	@cd Decorator && $(MAKE)
	@cd Proxy && $(MAKE)
	

clean:
	@cd AdaptorClass && $(MAKE) clean
	@cd AdaptorObject && $(MAKE) clean
	@cd Bridge && $(MAKE) clean
	@cd Decorator && $(MAKE) clean
	@cd Proxy && $(MAKE) clean


